paths:
  workdir: ./data
  models: ./models
  results: ./results
  logs: ./logs
  figures: ./figures

datasets:
  GEUVADIS:
    path: "/mnt/89ea702f-c213-4e9a-acb8-8c72a41b672e/Documents/PYTHON/RNASeqAnalysis/data/raw"
    counts_file: "Geuvadis.all.csv"
    metadata_file: "Geuvadis.SraRunTable.txt"
    annotation_file: "/mnt/89ea702f-c213-4e9a-acb8-8c72a41b672e/Documents/PYTHON/RNASeqAnalysis/data/raw/all_transcripts_strigtie_merged.gtf"

  HEART:
    path: /mnt/89ea702f-c213-4e9a-acb8-8c72a41b672e/Documents/PYTHON/RNASeqAnalysis/data/external/HEART/reg
    counts_file: "merged_heart_tpm.txt"
    metadata_file: "SraRunTable.txt"
    annotation_file: "/mnt/89ea702f-c213-4e9a-acb8-8c72a41b672e/Documents/PYTHON/RNASeqAnalysis/data/raw/all_transcripts_strigtie_merged.gtf"

  BRAIN0:
    path: "/mnt/89ea702f-c213-4e9a-acb8-8c72a41b672e/Documents/PYTHON/RNASeqAnalysis/data/external/BRAIN0/reg"
    counts_file: "brain0.TPM.csv"
    metadata_file: "SraRunTable.txt"
    annotation_file: "/mnt/89ea702f-c213-4e9a-acb8-8c72a41b672e/Documents/PYTHON/RNASeqAnalysis/data/raw/all_transcripts_strigtie_merged.gtf"

  BRAIN1:
    path: /mnt/89ea702f-c213-4e9a-acb8-8c72a41b672e/Documents/PYTHON/RNASeqAnalysis/data/external/BRAIN1/reg
    counts_file: "merged.brain.all.csv"
    metadata_file: "SraRunTable.txt"
    annotation_file: "/mnt/89ea702f-c213-4e9a-acb8-8c72a41b672e/Documents/PYTHON/RNASeqAnalysis/data/raw/all_transcripts_strigtie_merged.gtf"

models:
  train_dataset: GEUVADIS
  eval_dataset:
    - HEART
    - BRAIN0
    - BRAIN1

  value_to_predict: "sex"
  split_by: "sex"

model_params:
  model_type: "xgboost"
  feature_importance_method: "SHAP"
  use_CV: True
  config_file: "./rnaseqanalysis/models/models_config.json"
  feature_selection_method: top50
